#!/usr/bin/env bash

# environment
if [ -z "$APP_SERVER_GO_VERSION" ]; then
    source ${BASH_SOURCE%/*}/environment || exit $?
fi

# go version
if [ $(command -v gvm) ]; then
    source  ~/.gvm/scripts/gvm
    echo "=> Use ${APP_SERVER_GO_VERSION}"
    gvm use $APP_SERVER_GO_VERSION || exit $?
fi

# golang migrate
MIGRATE_PATH=$(which migrate)
if [[ "$MIGRATE_PATH" != *"$APP_SERVER_GO_VERSION"* ]]; then
    source ${BASH_SOURCE%/*}/db-migrate-install || exit $?
fi

# service directory list
shopt -s dotglob
shopt -s nullglob
cd ./service
SERVICE_NAMES=(*)
cd -

for SERVICE_NAME in "${SERVICE_NAMES[@]}"; do

    # run migrations
    if [ -d "./service/$SERVICE_NAME/migration" ]; then

        # load service specific environment
        source ${BASH_SOURCE%/*}/environment ./service/$SERVICE_NAME || exit $?

        URL="postgres://$APP_SERVER_DB_USER:$APP_SERVER_DB_PASSWORD@$APP_SERVER_DB_HOST:$APP_SERVER_DB_PORT/$APP_SERVER_DB_NAME?sslmode=disable"

        echo "=> Migration path ./service/$SERVICE_NAME/migration"

        migrate -verbose -path "./service/$SERVICE_NAME/migration" -database "$URL" -- up
    fi
done


