#!/usr/bin/env bash

NGINX_RUNNING=$(docker ps -a | grep "gomo-krakend")
if [[ ! -z "${NGINX_RUNNING}" ]]; then
    echo
    echo "=> Stopping krakend"
    echo
    docker stop gomo-krakend
    docker rm gomo-krakend
fi
