#!/usr/bin/env bash

echo
echo "=> Test service"
echo

# specific service
TEST_SERVICE=""
if [ -n "$1" ]; then
    TEST_SERVICE=$1
    shift
fi

# environment
if [ -z "$APP_SERVER_GO_VERSION" ]; then
    source ${BASH_SOURCE%/*}/environment || exit $?
fi

function test_services {
   
for f in "$BASE_DIRECTORY"/*; do

    if [ "$TEST_SERVICE" != "" ]; then
        if [ "service/$TEST_SERVICE" != "$f" ]; then
            echo "=> Test service - skipping $f"
            continue
        fi
    fi

    cd $f

    if [ -f "go.mod" ]; then
        echo "=> Test service directory - $f"
        export APP_SERVER_HOME=$(pwd)

        if [ $APP_SERVER_DB_SERVICE = "ci" ]; then
            if [ -f ".env.ci" ]; then
                echo "=> Test service - sourcing service .env.ci"
                source .env.ci
            fi
        else
            if [ -f ".env.development" ]; then
                echo "=> Test service - sourcing service .env.development"
                source .env.development
            fi
        fi

        echo "=> Test service - APP_SERVER_HOME - ${APP_SERVER_HOME}"
        go test -v -cover -count 1 ./... || exit $?
    fi
    cd -
done

}

# service
BASE_DIRECTORY="service"
test_services;

# service examples
BASE_DIRECTORY="service/example"
test_services;
